services:
  apex-platform:
    image: ghcr.io/lzhen228/apex-backend:latest
    container_name: apex-platform
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      JWT_SECRET: ${JWT_SECRET}
      APEX_FEISHU_ENABLED: ${APEX_FEISHU_ENABLED:-true}
      APEX_FEISHU_APP_ID: ${APEX_FEISHU_APP_ID:-cli_a946029d58f91bb4}
      APEX_FEISHU_APP_SECRET: ${APEX_FEISHU_APP_SECRET}
      APEX_FEISHU_REDIRECT_URI: ${APEX_FEISHU_REDIRECT_URI:-https://47-94-120-15.sslip.io/login}
      APEX_FEISHU_AUTHORIZE_URL: ${APEX_FEISHU_AUTHORIZE_URL:-https://open.feishu.cn/connect/qrconnect/page/sso}
      APEX_FEISHU_ACCESS_TOKEN_URL: ${APEX_FEISHU_ACCESS_TOKEN_URL:-https://open.feishu.cn/open-apis/authen/v1/access_token}
    restart: unless-stopped
    networks:
      - apex-network

  apex-frontend:
    image: ghcr.io/lzhen228/apex-frontend:latest
    container_name: apex-frontend
    ports:
      - "8090:3000"
    depends_on:
      - apex-platform
    restart: unless-stopped
    networks:
      - apex-network

networks:
  apex-network:
    driver: bridge
